import base64
import os
from openai import OpenAI
from dotenv import load_dotenv
load_dotenv()


def _openai_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by OpenAI image model.
k
    Requires:
        pip install openai

    Env var:
        OPENAI_API_KEY
    """

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set.")

    client = OpenAI(api_key=api_key)

    resp = client.images.generate(
        model="gpt-image-1.5",
        prompt=prompt,
        size="1024x1024",
        n=1
    )

    # OpenAI returns base64 image data
    if not resp.data or not resp.data[0].b64_json:
        raise RuntimeError("No image returned from OpenAI.")

    return base64.b64decode(resp.data[0].b64_json)